In [5]:
#1
def fib(z):
    if z == 1 or z == 2:
        return 1
    return fib(z - 1) + fib(z - 2)


print(fib(int(input())))

 6


8


In [37]:
#2
def p(x):
    return(all([x % i != 0 for i in range(2, int(x ** 0.5) + 1)]))


def raz(a):
    if a == 1:
        return []
    for i in range(2, int(a ** 0.5) + 1):
        if a % i == 0 and p(i):
            return [i] + raz(a // i)
    return [a]


print(raz(120))

[2, 2, 2, 3, 5]


In [60]:
#3
def func(a, b):
    if a == 0:
        return (0, 1, b)
    x, y, d = func(b % a, a)
    return y - (b // a) * x, x, d

print(func(5, 3))

(-1, 2, 1)


In [46]:
#4
def tre(size, symb):
    if size == 1:
        print(symb * ((n - size) // 2 + 1))
        return
    if size == 0:
        return
    print(symb * ((n - size) // 2 + 1))
    tre(size - 2, symb)
    print(symb * ((n - size) // 2 + 1))

n = 6
s = 'c'
tre(n, s)

c
cc
ccc
ccc
cc
c


In [2]:
import numpy as np

In [71]:
#5
t, m = map(int, input().split())
a = np.zeros((t, m))
z = 1
n = 0
while n <= min(t, m) // 2:
    if z <= t * m:
         for i in range(n, m - n):
            a[n][i] = z
            z += 1

    if z <= t * m:
        for i in range(n + 1, t - n):
            a[i][m - n - 1] = z
            z += 1
    
    if z <= t * m and t - n - 1 > n:
        for i in range(m - n - 2, n - 1, -1):
            a[t - n - 1][i] = z
            z += 1

    if z <= t * m and m - n - 1 > n:
        for i in range(t - n - 2, n, -1):
            a[i][n] = z
            z += 1
    
    n += 1

print(a)

 6 7


[[ 1.  2.  3.  4.  5.  6.  7.]
 [22. 23. 24. 25. 26. 27.  8.]
 [21. 36. 37. 38. 39. 28.  9.]
 [20. 35. 42. 41. 40. 29. 10.]
 [19. 34. 33. 32. 31. 30. 11.]
 [18. 17. 16. 15. 14. 13. 12.]]


In [3]:
#6
def least_squares(x, y):
    k = (np.mean(x*y) - np.mean(x) * np.mean(y)) / (np.mean(x*x) - np.mean(x) ** 2)
    b = np.mean(y) - k * np.mean(x)
    return k, b


x = np.array([1, 2, 1, 2, 3, 1, 1])
y = np.array([5, 5, 6, 5, 7, 5, 2])
print(*least_squares(x, y))

1.0769230769230778 3.3076923076923066


In [18]:
#7
#n, m = map(int, input().split())
#a = [list(map(float, input().split())) for i in range(n)]
a = [[1, -1, 4], [1, 2, 10]]
b = []
for i in a:
    b.append(i.pop(-1))
A = np.array(a)
B = np.array(b)
x = np.linalg.solve(A, B)
print(*x)

6.0 2.0


In [6]:
#8
import matplotlib.pyplot as plt
import random


sigma = 0.7
x = np.arange(20)
k = 2
b = 3
y = k * x + b

yg = y + np.array([random.gauss(0, sigma) for i in range(20)])

k1, b1 = least_squares(x, yg)
print(k1, b1)

2.0093656407621148 2.932270859808277
